[__WEBSITE_USER__]
listen = /var/run/php/$pool.sock
listen.allowed_clients = 127.0.0.1
listen.owner = $pool
listen.group = nginx
listen.mode = 0660
user = $pool
group = $pool
pm = __PHP_PM_TYPE__
pm.max_children = __PM_MAX_CHILDREN__
pm.start_servers = __PM_START_SERVERS__
pm.min_spare_servers = __PM_MIN_SPARE_SERVER__
pm.max_spare_servers = __PM_MAX_SPARE_SERVER__
pm.process_idle_timeout = 20
pm.max_requests = __PM_MAX_REQUEST__
;slowlog = __SLOW_LOG__
chdir = /
php_admin_value[error_log] = __ERROR_LOG_PATH__
php_admin_flag[log_errors] = on
php_value[session.save_handler] = files
php_value[session.save_path]    = __SESSION_PATH__
php_admin_value[disable_functions] = exec,system,passthru,shell_exec,proc_close,proc_open,dl,popen,show_source,posix_kill,posix_mkfifo,posix_getpwuid,posix_setpgid,posix_setsid,posix_setuid,posix_setgid,posix_seteuid,posix_setegid,posix_uname
php_admin_value[open_basedir] = /home/__OWNER_FOLDER__/__DOMAIN__/public_html/:/home/__OWNER_FOLDER__/__DOMAIN__/php/:/dev/urandom:/usr/share/php/:/dev/shm:/tmp:/var/tmp
;php_admin_value[allow_url_fopen] = Off
;php_admin_value[allow_url_include] = Off
security.limit_extensions = .php
php_admin_value[memory_limit] = __PHP_MEMORY_LIMIT__
php_admin_value[max_execution_time] = __PHP_MAX_EXECUTION_TIME__
php_admin_value[max_input_time] = __PHP_MAX_INPUT_TIME__
php_admin_value[post_max_size] = __PHP_POST_MAX_SIZE__
php_admin_value[upload_max_filesize] = __PHP_UPLOAD_MAX_FILESIZE__
