#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on Ubuntu             #
#                                                                    #
#                      McnVPS - MCN Technical                        #
#                       Website: https://mcnvps.net                  #
#                                                                    #
#              Please do not remove copyright. Thank!                #
######################################################################

wget -O install_new "https://raw.githubusercontent.com/phongnhadn1991/McnVPS/master/scripts/install_new"
bash install_new
rm -rf install_new
