fastcgi_cache __CACHE_ZONE__;
fastcgi_cache_bypass $skip_cache $http_authorization;
fastcgi_no_cache $skip_cache $http_authorization;
add_header X-Cache $upstream_cache_status;
add_header Last-Modified $date_gmt;
