location = /wp-login.php {
    limit_req zone=req_limit_per_ip burst=1 nodelay;
    include /etc/nginx/fastcgi_params;
    include /etc/nginx/nginx_limits.conf;

    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

    if (-f $request_filename) {
        fastcgi_pass unix:__PHP_SOCKET__;
    }
}
