location /sql { access_log off; log_not_found off; return 444; }
location /wp-content/updraft { access_log off; log_not_found off; return 444; }
location /wp-content/backups-dup-pro { access_log off; log_not_found off; return 444; }
location /wp-snapshots { access_log off; log_not_found off; return 444; }
location /wp-content/uploads/sucuri { access_log off; log_not_found off; return 444; }
location /wp-content/uploads/nginx-helper { access_log off; log_not_found off; return 444; }
location = /wp-config.php { access_log off; log_not_found off; return 444; }
location = /wp-links-opml.php { access_log off; log_not_found off; return 444; }
location = /wp-config-sample.php { access_log off; log_not_found off; return 444; }
location = /readme.html { access_log off; log_not_found off; return 444; }
location = /license.txt { access_log off; log_not_found off; return 444; }

location /wp-content/cache {
# Cache css & js files
    location ~* \.(?:css(\.map)?|js(\.map)?|.html)$ {
        add_header Access-Control-Allow-Origin *;
        access_log off;
        log_not_found off;
        expires 365d;
    }

    location ~ \.php$ { access_log off; log_not_found off; return 444; }
}
